#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[user]
name = "Roxy Light"
email = "{{ get . "email" | default "roxy@zombiezen.com" }}"

[ui]
diff-editor = ":builtin"  # disables noisy messages
merge-editor = "vscode"
revsets-use-glob-by-default = true
{{- if eq .chezmoi.os "windows" }}
editor = "code.cmd --wait"
{{- end }}

[aliases]
heads = [ "log", "--no-graph", "--revision=trunk() | (heads(immutable_heads().. ~ (present(@) & empty() & description(''))))", "--template=log_name"]
touch = ["metaedit", "--update-author-timestamp", "--quiet"]
mm = ["bookmark", "move", "main"]
mmp = ["bookmark", "move", "--to=first_parent(@)", "main"]
ba = ["bookmark", "advance"]
push-wip = ["git", "push", "--config=git.private-commits=private()"]

converge = ["util", "exec", "--", "jj-converge"]
domino = ["util", "exec", "--", "jj-domino"]
submit = ["util", "exec", "--", "jj-domino", "submit"]

# Frequently, I will keep a "private" bookmark
# that contains local-only changes that I don't want to share.
# (Usually these shim in some dev tools settings or something.)
# My working copy commit will then be a merge of the change I want and the "private" branch.
# This alias untangles the change(s) from the "private" branch.
rebase-public = ["rebase", "--revisions=private::@- & ~private", "--insert-after=first_parent(private+ & ::@)", "--insert-before=@"]
rbp = ["rebase-public"]

[fix.tools.gofmt]
command = ["gofmt"]
patterns = ["glob:'**/*.go'"]

[git]
private-commits = "private() | wip()"

[revsets]
# Default to the current branch (plus any sub-branches) and trunk().
log = "present(@) | ancestors((trunk()..present(@))::, 2) | trunk()"
bookmark-advance-to = "first_parent(@)"

[revset-aliases]
'fp' = 'first_parent(@)'
'fp(x)' = 'first_parent(x)'
'fp(x, depth)' = 'first_parent(x, depth)'
'branches_off(base, x)' = 'roots(base..x):: ~ ::x'
'branches_off(x)' = 'branches_off(trunk(), x)'
'private()' = 'description(glob:"private:*")'
'wip()' = 'description(glob:"wip:*") | diff_lines_added(glob:"*TODO(now)*")'

[template-aliases]
'commit_timestamp(commit)' = 'commit.author().timestamp()'

# Change the display of the time in `jj operation log`
# so the exact time is shown instead of "N minutes ago".
'format_time_range(time_range)' = '''
time_range.start().local().format("%Y-%m-%d %-I:%M:%S %p") ++
label("time", ", lasted ") ++ time_range.duration()
'''

# log_name and log_name_full_description are templates
# similar to builtin_log_compact and builtin_log_compact_full_description
# that use format_short_commit_header_prefer_names.
'log_name' = "log_name(self)"
'log_name(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    concat(
      format_short_commit_header_prefer_names(commit) ++ "\n",
      separate(" ",
        if(commit.empty(), empty_commit_marker),
        if(commit.description(),
          commit.description().first_line(),
          label(if(commit.empty(), "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''
'log_name_full_description' = "log_name_full_description(self)"
'log_name_full_description(commit)' = '''
if(commit.root(),
  format_root_commit(commit),
  label(
    separate(" ",
      if(commit.current_working_copy(), "working_copy"),
      if(commit.immutable(), "immutable", "mutable"),
      if(commit.conflict(), "conflicted"),
    ),
    concat(
      format_short_commit_header_prefer_names(commit) ++ "\n",
      separate(" ",
        if(commit.empty(), empty_commit_marker),
        if(commit.description(),
          commit.description().first_line(),
          label(if(commit.empty(), "empty"), description_placeholder),
        ),
      ) ++ "\n",
    ),
  )
)
'''

# format_short_commit_header_prefer_names is a template
# similar to the builtin format_short_commit_header
# but prefers showing bookmarks/tags over change IDs.
'format_short_commit_header_prefer_names(commit)' = '''
separate(" ",
  coalesce(
    separate(" ", commit.bookmarks(), commit.tags()),
    format_short_change_id_with_change_offset(commit),
  ),
  format_short_signature(commit.author()),
  format_timestamp(commit_timestamp(commit)),
  commit.working_copies(),
  format_short_commit_id(commit.commit_id()),
  format_commit_labels(commit),
  if(config("ui.show-cryptographic-signatures").as_boolean(),
    format_short_cryptographic_signature(commit.signature())
  ),
)
'''

[templates]
duplicate_description = '''
concat(
  "private: ",
  description.trim_end(),
  "\n\n(cherry picked from ",
  commit_id,
  ")\n",
)
'''

# I usually call the remote that is my fork of a repo "zombiezen".
# As such, I usually want to track all the active branches.
[remotes.zombiezen]
auto-track-bookmarks = "* ~ main ~ master"

[[--scope]]
--when.commands = ["status"]
[--scope.ui]
paginate = "never"

[[--scope]]
--when.commands = ["evolog"]
[--scope.template-aliases]
'commit_timestamp(commit)' = 'commit.committer().timestamp()'

[[--scope]]
--when.commands = ["diff", "show"]
[--scope.ui]
pager = "delta"
diff-formatter = ":git"
